tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
brew "openssl@1.1"
brew "libsass"
brew "nvm"
brew "readline"
brew "sqlite"
brew "xz"
brew "python@3.9"
brew "pipenv"
brew "postgresql", restart_service: true
brew "pyenv"
brew "tidy-html5"
brew "zlib"
brew "mongodb/brew/mongodb-community"
